spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Actuator Configs
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

logging.level.org.springframework=INFO