spring.application.name=Backend

# DB Configurations (get these from environment variables)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Mercado Pago Token (get this from environment variable)
MP_ACCESS_TOKEN=${MP_ACCESS_TOKEN}